title: Lewis Goddard
description: ...
lang: en-GB
# the base hostname & protocol for your site
url: "https://lewisgoddard.me.uk"
baseurl: /

permalink: /:title/
page_excerpts: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
theme: jekyll-theme-cayman
