title: Lewis Goddard
description: ...
# the base hostname & protocol for your site
#url: "https://lewisgoddard.me.uk"
url: "https://website-dh0.pages.dev"
baseurl: /

permalink: /:title/
page_excerpts: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
theme: jekyll-theme-cayman
