title: Lewis Goddard
description: ...
# the base hostname & protocol for your site
#url: "https://lewisgoddard.me.uk"
url: "https://lewisgoddard.github.io"
baseurl: /website

permalink: /:title/
page_excerpts: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
theme: jekyll-theme-cayman
